apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodejs
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
  name: ingress-to-nodejs
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nodejs-nodeapp
          servicePort: http
